### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by mcollina** [fastify/releasify#12]
```
{ Deprecation: [@octokit/rest] "number" parameter is deprecated for "GET /repos/:owner/:repo/issues/:issue_number/labels", use "issue_number" instead
    at Object.keys.forEach.parameterName (/Users/matteo/.nvm/versions/node/v10.15.2/lib/node_modules/@fastify/releasify/node_modules/@octokit/rest/plugins/validate/validate.js:34:22)
    at Array.forEach (<anonymous>)
    at validate (/Users/matteo/.nvm/versions/node/v10.15.2/lib/node_modules/@fastify/releasify/node_modules/@octokit/rest/plugins/validate/validate.js:17:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'Deprecation' }
{ Deprecation: [@octokit/rest] "number" parameter is deprecated for "GET /repos/:owner/:repo/issues/:issue_number/labels", use "issue_number" instead
    at Object.keys.forEach.parameterName (/Users/matteo/.nvm/versions/node/v10.15.2/lib/node_modules/@fastify/releasify/node_modules/@octokit/rest/plugins/validate/validate.js:34:22)
    at Array.forEach (<anonymous>)
    at validate (/Users/matteo/.nvm/versions/node/v10.15.2/lib/node_modules/@fastify/releasify/node_modules/@octokit/rest/plugins/validate/validate.js:17:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'Deprecation' }
```

**Comment by Eomm** [comment]
Updating dep to `"@octokit/rest": "^16.24.1"` solve it.
Will land with #9

**Comment by Eomm** [comment]
This could be fixed now, could you confirm?

**Comment by mcollina** [comment]
Confirmed.
