### ISSUE TITLE
Type error is thrown, when repository in package.json is a string, not an object 

### ISSUE THREAD

**Issue by capaj** [fastify/releasify#185]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

x

### Plugin version

x

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

Ubuntu 21.04

### Description

a valid value like:
`"repository": "github:nearform/mercurius-apollo-tracing",`

causes error like this:
```
    TypeError: Cannot destructure property 'owner' of 'parseGitUrl(...)' as it is null.
        at github (/home/capaj/.nvm/versions/node/v16.7.0/lib/node_modules/releasify/lib/github.js:7:11)
        at module.exports (/home/capaj/.nvm/versions/node/v16.7.0/lib/node_modules/releasify/lib/commands/draft.js:63:18)
        at async module.exports (/home/capaj/.nvm/versions/node/v16.7.0/lib/node_modules/releasify/lib/commands/publish.js:106:21)
        at async Command.func (/home/capaj/.nvm/versions/node/v16.7.0/lib/node_modules/releasify/lib/cli.js:18:7)
```

### Steps to Reproduce

use 
`"repository": "github:nearform/mercurius-apollo-tracing",`

### Expected Behavior

no type error is thrown for plain string value in `repository`

**Comment by climba03003** [comment]
I think it is supported.
https://github.com/jonschlinkert/parse-github-url/blob/master/test.js#L28

Maybe file a bug report to `parse-github-url

**Comment by capaj** [comment]
oh yeah, the problem is not in `parse-github-url`.
Problem is releasify always assumes that the repository value in pkg.json is an object. It can be jsut a plain string. 
I will rephrase the issue.
