### ISSUE TITLE
Error doing publishing

### ISSUE THREAD

**Issue by mcollina** [fastify/releasify#36]
## 🐛 Bug Report

```
[1588343990110] ERROR (HttpError): Not Found
    HttpError: Not Found
        at /Users/matteo/.nvm/versions/node/v12.16.1/lib/node_modules/releasify/node_modules/@octokit/request/dist-node/index.js:66:23
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async module.exports (/Users/matteo/.nvm/versions/node/v12.16.1/lib/node_modules/releasify/lib/commands/publish.js:155:27)
        at async Command.func (/Users/matteo/.nvm/versions/node/v12.16.1/lib/node_modules/releasify/lib/cli.js:18:7)
ERROR: Something went wrong creating the relase on GitHub.
The 'npm publish' and 'git push' has been done!
Consider creating a release on GitHub by yourself with this message:
```

## To Reproduce

```
releasify publish -s major -m --npm-dist-tag next --gh-release-prerelease --npm-otp
```

## Expected behavior

The release should be created on gh.

**Comment by Eomm** [comment]
It seems the installation is broken, did you tried to reinstall it?

**Comment by Eomm** [comment]
I would like to motivate why I think it is broken: because I see nvm in the path, and npm - g install it on the specific platform so, changing node major version with nvm, would require a new installation of releasify

**Comment by mcollina** [comment]
I uninstalled and reinstalled and it's still the same error.

**Comment by Eomm** [comment]
I had an error due to the git precommit hook, I will re-try to replicate soon
